# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
