# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160812_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='album_group',
            field=models.ForeignKey(default='unnamed', on_delete=django.db.models.deletion.CASCADE, to='gallery.AlbumGroup'),
        ),
    ]
