# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20160813_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_group',
            field=models.ForeignKey(default='unnamed', on_delete=django.db.models.deletion.CASCADE, related_name='group', to='gallery.AlbumGroup'),
        ),
    ]
